//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Selling
    {
        public int Sell_ID { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Customer { get; set; }
        public Nullable<byte> Count { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual tbl_Customers tbl_Customers { get; set; }
        public virtual tbl_Product tbl_Product { get; set; }
    }
}
