//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tbl_Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Customers()
        {
            this.tbl_Selling = new HashSet<tbl_Selling>();
        }
    
        public int Customer_ID { get; set; }
        [Required(ErrorMessage ="Bu alaný boþ býrakamazsýnýz")]
        [StringLength(50,ErrorMessage ="En fazla 50 karakter girebilirsiniz")]
        public string Customer_Name { get; set; }
        [Required(ErrorMessage = "Bu alaný boþ býrakamazsýnýz")]
        [StringLength(50, ErrorMessage = "En fazla 50 karakter girebilirsiniz")]
        public string Customer_Surname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Selling> tbl_Selling { get; set; }
    }
}
